### ISSUE TITLE
What should I do if the server is particularly memory hungry?

### ISSUE THREAD

**Issue by allcdn** [Kkevsterrr/geneva#42]
What should I do if the server is particularly memory hungry?

**Comment by Kkevsterrr** [comment]
Sorry I missed this. Under the hood, Geneva's engine is set up to record the packets it sees in memory (since we originally wrote that functionality to record our experiments for later analysis). You can turn that off by just setting `save_seen_packets=False` in the engine. (The packets it saved are never sent anywhere; it just sits in memory or written to a local pcap)
